# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32cf8ead28e454d518d342c24032c057c7e71bdcc43a013dd564a4d464cc498f2f5bef4c942de6104002c303963797b26abbbed63671fb21eb20dec1b6c8de62

test:
  secret_key_base: be1ab1edf6270f7bd381af4372a23fb4be8cd964f9f6323094227b7e5fe91835fdce6300f012ec8f6de11497dfde8f871f34bad47473c45af2522bcf4a1c7b68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
